# Generated by Django 5.1.3 on 2025-05-12 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
    ]
