# Generated by Django 5.1.3 on 2025-05-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
