# Generated by Django 5.1.3 on 2025-05-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
